### ISSUE TITLE
Ubuntu Install Error

### ISSUE THREAD

**Issue by ghjohnny** [Noctem/pogeo#1]
Running setup.py install for pogeo: started
    Running setup.py install for pogeo: finished with status 'error'
    Complete output from command /home/user/.pyenv/versions/3.6.0/envs/general/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vh6kncfu/pogeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q857iffe-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.pyenv/versions/3.6.0/envs/general/include/site/python3.6/pogeo:
    running install
    running build
    running build_ext
    building 'pogeo' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/geometry
    creating build/temp.linux-x86_64-3.6/geometry/base
    creating build/temp.linux-x86_64-3.6/geometry/strings
    creating build/temp.linux-x86_64-3.6/geometry/util
    creating build/temp.linux-x86_64-3.6/geometry/util/coding
    creating build/temp.linux-x86_64-3.6/geometry/util/math
    creating build/temp.linux-x86_64-3.6/geometry/util/math/exactfloat
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/base/int128.cc -o build/temp.linux-x86_64-3.6/geometry/base/int128.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/base/logging.cc -o build/temp.linux-x86_64-3.6/geometry/base/logging.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/base/stringprintf.cc -o build/temp.linux-x86_64-3.6/geometry/base/stringprintf.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    geometry/base/stringprintf.cc: In function ‘void StringAppendV(std::string*, const char*, __va_list_tag*)’:
    geometry/base/stringprintf.cc:23:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if ((result >= 0) && (result < sizeof(space))) {
                                                  ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/base/strtoint.cc -o build/temp.linux-x86_64-3.6/geometry/base/strtoint.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/base/strtoint.cc:9:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/strings/split.cc -o build/temp.linux-x86_64-3.6/geometry/strings/split.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/base/strtoint.h:38,
                     from geometry/strings/split.cc:15:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/strings/stringprintf.cc -o build/temp.linux-x86_64-3.6/geometry/strings/stringprintf.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    geometry/strings/stringprintf.cc: In function ‘std::string StringPrintfVector(const char*, const std::vector<std::basic_string<char> >&)’:
    geometry/strings/stringprintf.cc:31:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < v.size(); ++i) {
                                  ^
    In file included from geometry/base/logging.h:23:0,
                     from geometry/strings/stringprintf.cc:11:
    geometry/base/macros.h:79:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     #define arraysize(array) (sizeof(ArraySizeHelper(array)))
                                                             ^
    geometry/strings/stringprintf.cc:34:30: note: in expansion of macro ‘arraysize’
       for (int i = v.size(); i < arraysize(cstr); ++i) {
                                  ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/strings/strutil.cc -o build/temp.linux-x86_64-3.6/geometry/strings/strutil.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/strings/strutil.h:48,
                     from geometry/strings/strutil.cc:5:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    geometry/strings/strutil.cc: In function ‘bool DictionaryParse(const string&, std::vector<std::pair<std::basic_string<char>, std::basic_string<char> > >*)’:
    geometry/strings/strutil.cc:483:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < entries.size(); ++i) {
                                        ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/util/coding/coder.cc -o build/temp.linux-x86_64-3.6/geometry/util/coding/coder.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/util/coding/varint.h:22,
                     from geometry/util/coding/coder.h:16,
                     from geometry/util/coding/coder.cc:7:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    In file included from geometry/util/coding/coder.cc:7:0:
    geometry/util/coding/coder.h: In member function ‘void Encoder::putfloat(float)’:
    geometry/util/coding/coder.h:361:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual[sizeof(f) == sizeof(v) ? 1 : -1];
                    ^
    geometry/util/coding/coder.h: In member function ‘void Encoder::putdouble(double)’:
    geometry/util/coding/coder.h:368:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual[sizeof(d) == sizeof(v) ? 1 : -1];
                    ^
    geometry/util/coding/coder.h: In member function ‘float Decoder::getfloat()’:
    geometry/util/coding/coder.h:410:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual[sizeof(f) == sizeof(v) ? 1 : -1];
                    ^
    geometry/util/coding/coder.h: In member function ‘double Decoder::getdouble()’:
    geometry/util/coding/coder.h:418:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual[sizeof(d) == sizeof(v) ? 1 : -1];
                    ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/util/coding/varint.cc -o build/temp.linux-x86_64-3.6/geometry/util/coding/varint.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/util/coding/varint.h:22,
                     from geometry/util/coding/varint.cc:6:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/util/math/exactfloat/exactfloat.cc -o build/temp.linux-x86_64-3.6/geometry/util/math/exactfloat/exactfloat.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    geometry/util/math/exactfloat/exactfloat.cc: In member function ‘std::string ExactFloat::ToStringWithMaxDigits(int) const’:
    geometry/util/math/exactfloat/exactfloat.cc:343:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (exp10 >= digits.size()) {
                                    ^
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/home/user/.pyenv/versions/3.6.0/envs/general/include -I/home/user/.pyenv/versions/3.6.0/include/python3.6m -c geometry/util/math/mathlimits.cc -o build/temp.linux-x86_64-3.6/geometry/util/math/mathlimits.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/util/math/mathlimits.h:18,
                     from geometry/util/math/mathlimits.cc:6:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    In file included from geometry/util/math/mathlimits.cc:6:0:
    geometry/util/math/mathlimits.h: At global scope:
    geometry/util/math/mathlimits.h:97:79: error: field initializer is not constant
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: field initializer is not constant
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:97:79: error: field initializer is not constant
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: field initializer is not constant
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:97:79: error: field initializer is not constant
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: field initializer is not constant
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers" [enabled by default]
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by Noctem** [comment]
G++ ≥ 6 or a recent version of Clang/LLVM are currently required to build from source. But binary wheels are available on PyPI for 64-bit distros.
```bash
pip3 install pogeo
```

**Comment by xakiru** [comment]
I installed the latest versions, of gcc with the latest versions of Clang/LLVM.

I still get the same issue  : 
geometry/util/math/mathlimits.h:135:28: error: field initializer is not constant
   static const Type kMax = kPosMax; \

All other errors are showing "field initializer is not constant"

Please help, 
Thanks,

**Comment by Noctem** [comment]
Are you sure you're using the new versions?
```bash
export CC=g++-6
export CXX=g++-6
```
[You can see how Travis compiled it on Ubuntu 14.04.](https://travis-ci.org/Noctem/pogeo/jobs/203089158) (also [with clang](https://travis-ci.org/Noctem/pogeo/jobs/203089157))

And is there a reason you can't use a binary wheel from PyPI? They're now available for Linux x86_64 and i686 for Python 3.3 through 3.6.

**Comment by xakiru** [comment]
Still the same issue, after i did the export command ....

and here what it says when I try to install the binary wheel : 

pip install pogeo-0.2.0-cp36-cp36m-manylinux1_x86_64.whl
=> pogeo-0.2.0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.

uname -a
=> Linux vps24t 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTT 2016 x86_64 x86_64 x86_64 GNU/Linux

I got Ubuntu 14.04.5 LTS.
I'm not sure what is missing.

**Comment by xakiru** [comment]
My bad, I finally fixed this.

```
export CC=g++-6
export CXX=g++-6
```

```
alias python=python3.6
alias pip=pip3.6
```

did the trick.
Thank you

**Comment by Noctem** [comment]
Great, you're welcome.

By the way, you shouldn't have to manually download the wheel. `pip3 install pogeo` should just work.

Also, I don't know if you put those in your .bashrc/.zshrc or not, but if you're going to permanently set them I would do `CC=gcc-6`. `CC` should have the C version, but I set the C++ version for both on this since I think setuptools only looks at `CC`.
