### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by ibuckshot5** [Noctem/pogeo#2]
I keep getting this error when trying to install requirements for Monocle, here is the error below:

`Command "c:\users\ibuckshot\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ibuckshot\\AppData\\Local\\Temp\\pip-build-1ohqe50f\\pogeo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close()
;exec(compile(code, __file__, 'exec'))" install --record C:\Users\ibuckshot\AppData\Local\Temp\pip-5pyv_w_7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ibuckshot\AppData\Local\Temp\pip-build-1ohqe50f\pogeo\`

Am I doing something wrong?

Edit: [Full Code](http://pastebin.com/wN1ZR0bH)

**Comment by Noctem** [comment]
Either use Python 3.6 (recommended anyways) or 64-bit.

Current binary availability:

| Platform | Wheel |
| ------------- | ------------- |
| Windows x86 3.5  | No |
| Windows x64 3.5  | Yes  |
| Windows x86 3.6 | Yes |
| Windows x64 3.6 | Yes |
| Linux x86 3.5  | Yes |
| Linux x64 3.5  | Yes  |
| Linux x86 3.6 | Yes |
| Linux x64 3.6 | Yes |
| macOS x64 3.5  | Yes  |
| macOS x64 3.6 | Yes |

I could probably be persuaded to compile one for x86 3.5 if there's an actual need for using that, but it would be better to just upgrade Python.

**Comment by ibuckshot5** [comment]
Alright, it worked. Thanks!
